Models/ErrorViewModel.cs
using System;

namespace MyWebsite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyWebsite.Models;

namespace MyWebsite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Resume()
        {
            return View();
        }
        public IActionResult Work()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/WorkController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyWebsite.Models;

namespace MyWebsite.Controllers
{
    public class WorkController : Controller
    {
        private readonly ILogger<WorkController> _logger;

        public WorkController(ILogger<WorkController> logger)
        {
            _logger = logger;
        }

        public IActionResult Urc()
        {
            return View();
        }

        public IActionResult SpriteEditor()
        {
            return View();
        }

        public IActionResult DayPlanner()
        {
            return View();
        }

        public IActionResult LMS()
        {
            return View();
        }

        public IActionResult Blackjack()
        {
            return View();
        }

        public IActionResult ChessBrowser()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index Page";
}

<head>
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />
</head>

<body style="background-color:gainsboro;">
    <div>
        <div style="width: 60%; position:relative; float:left;">
            <div style="position:relative; float:left; margin-top: 50px; margin-right: 50px;">
                <img src="~/images/Portfolio_Photo_Japan.PNG" alt="Portfolio Picture" size="flex" min-width="750" min-height="1334" style="width:100%; height:auto;">
            </div>
        </div>

        <div style="width: 40%; float:right; font-size: 120%; font-family: Lucida Console">
            <br />
            <br />
            <hr style="height:1px;border:none;color:#333;background-color:#333;" />
            <p style="font-size: 250%; text-align: center; font-family: Lucida Console" ;">
                About Me
            </p>
            <p id="earlyfade">
                Hey there!
            </p>
            <p id="midfade">
                I’m Nick. An undergraduate student at the University of Utah, pursuing a bachelors degree in Computer Science. The more time I spend programming (both in and out of school), the more I’ve found how much I enjoy collaborating with a team, challenging myself, and growing as a developer.
            </p>
            <p id="midfade">
                I love travelling, spending time with friends and family, gaming, and the outdoors. My favorite food is sushi, and I can drink coffee all day long.
            </p>
            <p id="latefade">
                Feel free to contact me using any of the following:
            </p>
            <p id="latefade">
                Email : nicholasnord@gmail.com
            </p>
            <p id="latefade">
                Cell : (801) 971-7336.
            </p>
            <p id="latefade">
                Github : <a href=https://github.com/Nordicade> https://github.com/Nordicade </a>
            </p>
            <p id="latefade">
                LinkedIn : <a href=https://www.linkedin.com/in/nicholas-nord-644220194 /> https://www.linkedin.com/in/nicholas-nord-644220194/ </a>
            </p>
            <hr style="height:1px;border:none;color:#333;background-color:#333;" />


            <br />
            <br />

        </div>
    </div>
</body>

Views/Home/Resume.cshtml
@{
    ViewData["Title"] = "Resume Page";
}
<head>
    <link href="~/css/resume.css" rel="stylesheet" type="text/css" />
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <div class="text-center center-align-div">
        <button type="button" class="btn btn-secondary btn-lg btn-block download">Download PDF</button>
    </div>
    <br />
    <hr style="height:1px;border:none;color:#333;background-color:#333;" />
    <br />
    <div>
        <iframe src="~/images/resume.pdf" class="full-size">
        </iframe>
        <a href="~/images/resume.pdf"> </a>

    </div>
</body>

Views/Home/Work.cshtml
@{
    ViewData["Title"] = "Work Page";
}
<head>
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />
    <link href="~/css/work.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <hr style="height:1px;border:none;color:#333;background-color:#333;" />

    <div class="row">
        <div class="col">
            <p>
                <a asp-area="" asp-controller="Work" asp-action="Urc">
                    <img src="~/images/4540/URC_1.PNG" alt="4540 URC Project PNG" width="350" height="350">
                </a>
            </p>
            <p class="text-center">
                University Research Coordinator
            </p>
        </div>
        <div class="col">
            <p>
                <a asp-area="" asp-controller="Work" asp-action="SpriteEditor">
                    <img src="~/images/3505/Sprite_editor_Capture.PNG" alt="Sprite Editor Project PNG" width="350" height="350">
                </a>
            <p class="text-center">
                Sprite Editor
            </p>
        </div>
        <div class="col">
            <p>
                <a asp-area="" asp-controller="Work" asp-action="DayPlanner">
                    <img src="~/images/personal/DayPlanner1.PNG" alt="4540_1" width="350" height="350">
                </a>
            </p>
            <p class="text-center">
                Day Planner Mobile App
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <p>
                <a asp-area="" asp-controller="Work" asp-action="LMS">
                    <img src="~/images/5530/LMS_1.PNG" alt="5530 LMS Project PNG" width="350" height="350">
                </a>
            </p>
            <p class="text-center">
                LMS Database
            </p>
        </div>
        <div class="col">
            <p>
                <a asp-area="" asp-controller="Work" asp-action="Blackjack">
                    <img src="~/images/3505/BlackJack_Capture.PNG" alt="Blackjack Tutorial Project PNG" width="350" height="350">
                </a>
            </p>
            <p class="text-center">
                Blackjack Tutorial
            </p>
        </div>
        <div class="col">
            <p>
                <a asp-area="" asp-controller="Work" asp-action="ChessBrowser">
                    <img src="~/images/5530/Chess_Browser_1.PNG" alt="Chess Browser Project PNG" width="350" height="350">
                </a>
            </p>

            <p class="text-center">
                Chess Browser
            </p>
        </div>
    </div>

</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyWebsite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/resume.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  navbar-light bg-light" id="mynavbar">
            <a class="navbar-brand" style="font-size:250%;" asp-area="" asp-controller="Home" asp-action="Index"><b>Nicholas Nord</b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav" style="text-align:center;">
                    <li class="nav-item">
                        <a class="nav-link">/</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Resume">Resume</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link">/</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Work">Work</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Work/Urc.cshtml
@{
    ViewData["Title"] = "Urc";
}
<head>
    <link href="~/css/work.css" rel="stylesheet" type="text/css" />
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />

</head>
<meta content="width=device-width, initial-scale=1.0">

<body>
    <div style="margin-top:50px; width:100%; height:100%; color:black;">
        <p class="text-center" style="font-size: 200%;">
            <b>UNIVERSITY RESEARCH COORDINATOR - C#</b>
        </p>
        <div style="width: 58%; position:relative; float:left; font-size: 120%;">
            <br />
            <br />
            <hr style="height:1px;border:none;color:#333;background-color:#333;" />

            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="6"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="7"></li>
                </ol>
                <div class="carousel-inner" role="listbox" style=" width:100%; height: 500px !important;">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="~/images/4540/URC_1.PNG" id="urc_1" alt="1 URC slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="~/images/4540/URC_2.PNG" id="urc_2" alt="2 URC slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="~/images/4540/URC_3.PNG" id="urc_3" alt="3 URC slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="~/images/4540/URC_4.PNG" id="urc_4" alt="4 URC slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="~/images/4540/URC_5.PNG" id="urc_5" alt="5 URC slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="~/images/4540/URC_6.PNG" id="urc_6" alt="6 URC slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="~/images/4540/URC_7.PNG" id="urc_7" alt="7 URC slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="~/images/4540/URC_8.PNG" id="urc_8" alt="8 URC slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <hr style="height:1px;border:none;color:#333;background-color:#333;" />
            <br />
            <br />
        </div>


        <div style="width: 40%; position:relative; float:right; font-size: 120%;">
            <br />
            <br />
            <hr style="height:1px;border:none;color:#333;background-color:#333;" />
            <p>
                For my CS 4540 - Web architecture course, I had used C#, ASP Core, and SQL to create a MVC full stack website. The purpose of this assignment was to create a website that would pair students seeking research opportunities with professors that could use help with their research. I started this assignment by writing HTML and CSS by hand. This was my first experience dealing with the front-end; and was a great learning experience and taught me a lot about the full stack, user roles, and hosting/managing a website).
            </p>
            <p>
                It didn’t take long to find out that bootstrap was a better way to orient a lot of the front-end elements. I also added a SQL back-end that was hosted on AWS server using IIS Express. This project progressed to the point where API endpoints and AJAX methods were included to create single page web applications that can query and modify the backend and display results to the view without having to refresh the page. This involved an AJAX method that would use elements passed in from the controller via a viewbag and then sending a JSON object to the API method. Lastly, I teamed up with a few other classmates and merged our work together to create a final product with even more features, such as a single page web application for messaging. (Complete with a customized HTML/CSS front-end) The final product also included some data analytics available for moderators of the web page to view, providing detailed information which can guide the direction of the site.
            </p>
            <p>
                Due to this program being a school assignment, the code is within a private github repository. If you are interested in seeing the code, feel free to email me and I will provide temporary viewing access.
            </p>
            <hr style="height:1px;border:none;color:#333;background-color:#333;" />
            <br />
            <br />
        </div>
    </div>
</body>